replicaCount: 1

image:
  repository: 667950714614.dkr.ecr.us-east-1.amazonaws.com/asset-renderer 
  pullPolicy: Always
  tag: "prod"

fullnameOverride: "asset-renderer"

containerPort: 3000

service:
  type: NodePort
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/success-codes: '404'
    alb.ingress.kubernetes.io/group.name: main
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:667950714614:certificate/0b77c545-fab7-4f69-a27f-6f7c74bc61d6
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80},{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/scheme: internet-facing
  hosts:
    - host: test-asset-renderer.mobilesoftware.systems
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: asset-renderer
                port:
                  number: 80
          - path: /games/dreadstone-keep
            pathType: Prefix
            backend:
              service:
                name: asset-renderer
                port:
                  number: 80
  tls: []

resources:
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  requests:
    cpu: 100m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
  scaleDownSeconds: 3

tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "core"
    effect: "NoSchedule"

env:
   host: ""
   port: ""
   API_URL: ""
   AVATAR_CONTRACT: ""
   ITEM_CONTRACT: ""
   GEM_CONTRACT: ""
  